directories:
  script: scripts
  module: scripts/modules

# Environment variables
env:
  GIT_USER_NAME: "escapace"
  GIT_USER_EMAIL: "security@escapace.com"
  GIT_USER_SIGNINGKEY: "0xF29CCEBC83FD4525"

# Enable manage repository scripts
enable:
  - help

# Default script
default: help
