before_install:
- npm install -g npm
- npm install -g recce
install: npm install
script:
- ./manage trust-escapace
- ./manage ci
after_success:
- npm run report-coverage
language: node_js
env:
  global:
  - NPM_PUBLISH_BRANCHES="master next"
branches:
  only:
  - master
  - next
  - "/^new-.*$/"
  - "/^feat-.*$/"
  - "/^add-.*$/"
  - "/^change-.*$/"
  - "/^breaking-.*$/"
  - "/^deprecate-.*$/"
  - "/^remove-.*$/"
  - "/^fix-.*$/"
  - "/^sec-.*$/"
  - "/^security-.*$/"
  - "/^perf-.*$/"
  - "/^performance-.*$/"
  - "/^test-.*$/"
  - "/^tests-.*$/"
  - "/^v?\\d+\\.\\d+\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+$/"
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
node_js:
- node
