childConcurrency: 1
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@types/node'
  - esroll
  - typescript
onlyBuiltDependencies:
  - esbuild
  - lefthook
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - eslint
  - '@eslint/*'
  - semver
