version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    default_assignees:
      - "l5x"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
