#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description entrypoint for ci/cd
# @import github.com/escapace/stack-tools release/npmTravis

main ()
{
    verbose true
    strict true

    _ npmTravis
}
