on:
  workflow_call:
    outputs:
      value:
        description: 'Node.js version'
        value: ${{ jobs.main.outputs.value }}
jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.node_version.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - name: get node version
        id: node_version
        run: |
          echo "::set-output name=value::$(cat package.json | jq -r .engines.node | grep -oP '([0-9]+)\.([0-9]+)\.([0-9]+)' | head -n 1)"
