name: retention-policy

on:
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  retention-policy:
    runs-on: ubuntu-latest
    concurrency: retention-policy
    steps:
      - id: name
        name: name
        shell: bash
        run: |
          echo "value=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ steps.name.outputs.value }}
          package-type: 'npm'
          min-versions-to-keep: 10
